document.write('<table cellpadding="0" cellspacing="0" width="100%" bgcolor="ffffff">')
document.write('<tr align="center" background="bgd.gif">')
document.write('<td background="bgd.gif" height="26" width="12%"><a href="index.html"><font size="24px" color="2E2E2E"><b>Home</b></a></td>')
document.write('<td background="bgd.gif" height="26" width="12%"><a href="karma.html"><font size="24px" color="2E2E2E"><b>Karma</b></a></td>')
document.write('<td background="bgd.gif" height="26" width="15%"><a href="wars.html"><font size="24px" color="2E2E2E"><b>&nbsp;&nbsp;Wars</b></a></td>')
document.write('<td background="bgd.gif" height="26" width="16%"><a href="deutsch.html"><font size="24px" color="2E2E2E"><b>&nbsp;&nbsp;<img src="swiss-flag.jpg" height="56px" ></b></a></td>')
document.write('<td background="bgd.gif" height="26" width="30%"><a href="contact.html"><font size="24px" color="2E2E2E"><b>Contact</b></a></td>')
document.write('</tr>')
document.write('</table>')
document.write('<table bgcolor="3f5582" cellpadding="0" cellspacing="0" width="100%" height="2">')
document.write('<tr><td height="2">')
document.write('</td></tr></table>')
